.github/workflows/search-logs-client-publish.yml, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj, source/Energinet.DataHub.MessageArchive.Client/Energinet.DataHub.MessageArchive.Client.csproj, source/Energinet.DataHub.MessageArchive.Client/Helpers/QueryStringHelper.cs
=> adding abstraction packages

source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/SearchResultsDto.cs, source/Energinet.DataHub.MessageArchive.Client/Energinet.DataHub.MessageArchive.Client.csproj, source/Energinet.DataHub.MessageArchive.Client/MessageArchiveClient.cs
=> helper update for query

source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/SearchCriteria.cs, source/Energinet.DataHub.MessageArchive.Client/Energinet.DataHub.MessageArchive.Client.csproj, source/Energinet.DataHub.MessageArchive.EntryPoint/Models/SearchCriteria.cs, source/Energinet.DataHub.MessageArchive.EntryPoint/Repository/ArchiveReaderRepository.cs, source/Energinet.DataHub.MessageArchive.EntryPoint/Validation/SearchCriteriaValidation.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/Repositories/ArchiveReaderRepositoryTests.cs, source/Energinet.DataHub.MessageArchive.Tests/Validation/SearchCriteriaValidationTests.cs
receiverId added to searchcriteria and datetime validation changes
* #0000
=> receiverId added to searchcriteria and datetime validation changes

source/Energinet.DataHub.MessageArchive.EntryPoint/Models/SearchCriteria.cs, source/Energinet.DataHub.MessageArchive.EntryPoint/Repository/ArchiveReaderRepository.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/Repositories/ArchiveReaderRepositoryTests.cs
=> updated with role type criteria

source/Energinet.DataHub.MessageArchive.EntryPoint/Models/SearchCriteria.cs, source/Energinet.DataHub.MessageArchive.EntryPoint/Repository/ArchiveReaderRepository.cs, source/Energinet.DataHub.MessageArchive.EntryPoint/Validation/SearchCriteriaValidation.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/Repositories/ArchiveReaderRepositoryTests.cs, source/Energinet.DataHub.MessageArchive.Tests/Validation/SearchCriteriaValidationTests.cs
added include related search and parse
* #0000
=> added include related search and parse

source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/SearchCriteria.cs, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/SearchResultItemDto.cs, source/Energinet.DataHub.MessageArchive.Client/Energinet.DataHub.MessageArchive.Client.csproj, source/Energinet.DataHub.MessageArchive.Client/Helpers/QueryStringHelper.cs, source/Energinet.DataHub.MessageArchive.Client/MessageArchiveClient.cs
added endpoint name to client nuget
* #0000
=> added endpoint name to client nuget

source/Energinet.DataHub.MessageArchive.EntryPoint/Models/SearchCriteria.cs, source/Energinet.DataHub.MessageArchive.EntryPoint/Models/SearchResults.cs, source/Energinet.DataHub.MessageArchive.EntryPoint/Repository/ArchiveReaderRepository.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/Repositories/ArchiveReaderRepositoryTests.cs
=> added cosmos paging

source/Energinet.DataHub.MessageArchive.EntryPoint/Functions/ArchiveSearchRequestListener.cs
=> parse only if value exists in query else take default.

build/infrastructure/main/func-entrypoint.tf
=> adding func base url to keyvault

source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/SearchCriteria.cs, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/SearchResultsDto.cs, source/Energinet.DataHub.MessageArchive.Client/Energinet.DataHub.MessageArchive.Client.csproj, source/Energinet.DataHub.MessageArchive.Client/Helpers/QueryStringHelper.cs
=> paging client

source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/SearchCriteria.cs, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/SearchResultItemDto.cs, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/SearchResultsDto.cs, source/Energinet.DataHub.MessageArchive.Client/Energinet.DataHub.MessageArchive.Client.csproj, source/Energinet.DataHub.MessageArchive.EntryPoint/Startup.cs
=> updated client

source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj, source/Energinet.DataHub.MessageArchive.Client.Abstractions/IMessageArchiveClient.cs, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/MessageArchiveSearchCriteria.cs, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/MessageArchiveSearchResultItemDto.cs, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/MessageArchiveSearchResultItemErrorDto.cs, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/MessageArchiveSearchResultsDto.cs, source/Energinet.DataHub.MessageArchive.Client.Tests/Helpers/QueryStringHelperTests.cs, source/Energinet.DataHub.MessageArchive.Client/Energinet.DataHub.MessageArchive.Client.csproj, source/Energinet.DataHub.MessageArchive.Client/Helpers/QueryStringHelper.cs, source/Energinet.DataHub.MessageArchive.Client/MessageArchiveClient.cs
=> client model rename

source/Energinet.DataHub.MessageArchive.EntryPoint/BlobServices/BlobReader.cs
fixing bug where first page can be empty when reading blob files 
* #0000
=> read next page if any and first i empty

source/Energinet.DataHub.MessageArchive.EntryPoint/Repository/ArchiveReaderRepository.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/Repositories/ArchiveReaderRepositoryTests.cs
related message update, how to find related message. 
* #0000
=> related message update

source/Energinet.DataHub.MessageArchive.EntryPoint.WebApi/Startup.cs
removed usermiddleware
* #0000
=> removed usermiddleware

source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Models/MessageArchiveSearchCriteria.cs, source/Energinet.DataHub.MessageArchive.Client/Energinet.DataHub.MessageArchive.Client.csproj, source/Energinet.DataHub.MessageArchive.Client/Helpers/QueryStringHelper.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/Repositories/ArchiveReaderRepositoryTests.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/Repositories/ArchiveWriterRepositoryTests.cs, source/Energinet.DataHub.MessageArchive.Persistence/ArchiveSearchRepository.cs, source/Energinet.DataHub.MessageArchive.Reader/Models/SearchCriteria.cs, source/Energinet.DataHub.MessageArchive.Reader/Validation/SearchCriteriaValidation.cs, source/Energinet.DataHub.MessageArchive.Tests/Validation/SearchCriteriaValidationTests.cs
multi search rsm names and processtypes.
adding  includeResultsWithoutContent flag in search params.
* #0000
=> multi search rsm processtype

.github/workflows/cd.yml
Fix code coverage upload (job) in CD pipeline.
https://github.com/Energinet-DataHub/geh-message-archive/runs/6170301147?check_suite_focus=true
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/258
=> Ensure we install Azurite

source/Energinet.DataHub.MessageArchive.IntegrationTests/Repositories/ArchiveWriterRepositoryTests.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/WebApi/SearchLogsControllerTests.cs, source/Energinet.DataHub.MessageArchive.Persistence/ArchiveSearchRepository.cs
fixing include result with content criteria
* #0000
=> fixing include result with content criteria

source/Energinet.DataHub.MessageArchive.Persistence/ArchiveSearchRepository.cs
=> bug fix null array

source/Energinet.DataHub.MessageArchive.Common/Energinet.DataHub.MessageArchive.Common.csproj, source/Energinet.DataHub.MessageArchive.Common/StartupBase.cs, source/Energinet.DataHub.MessageArchive.EntryPoint.WebApi/Energinet.DataHub.MessageArchive.EntryPoint.WebApi.csproj, source/Energinet.DataHub.MessageArchive.EntryPoint.WebApi/Program.cs, source/Energinet.DataHub.MessageArchive.EntryPoint.WebApi/Startup.cs, source/Energinet.DataHub.MessageArchive.EntryPoint/Monitor/HealthCheckEndpoint.cs, source/Energinet.DataHub.MessageArchive.EntryPoint/Startup.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/Persistence/BlobArchiveTests.cs, source/Energinet.DataHub.MessageArchive.Persistence/Services/BlobReader.cs, source/Energinet.DataHub.MessageArchive.Processing/LogParsers/LogParserXml.cs
added  health checks in message archive
* #0000
=> add health checks

.github/workflows/cd.yml, .github/workflows/ci.yml, source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj, source/Energinet.DataHub.MessageArchive.Client.Tests/Energinet.DataHub.MessageArchive.Client.Tests.csproj, source/Energinet.DataHub.MessageArchive.Client/Energinet.DataHub.MessageArchive.Client.csproj, source/Energinet.DataHub.MessageArchive.Common/Energinet.DataHub.MessageArchive.Common.csproj, source/Energinet.DataHub.MessageArchive.EntryPoint.WebApi/Energinet.DataHub.MessageArchive.EntryPoint.WebApi.csproj, source/Energinet.DataHub.MessageArchive.EntryPoint/Energinet.DataHub.MessageArchive.EntryPoint.csproj, source/Energinet.DataHub.MessageArchive.IntegrationTests/Energinet.DataHub.MessageArchive.IntegrationTests.csproj, source/Energinet.DataHub.MessageArchive.Persistence/Energinet.DataHub.MessageArchive.Persistence.csproj, source/Energinet.DataHub.MessageArchive.Processing/Energinet.DataHub.MessageArchive.Processing.csproj, source/Energinet.DataHub.MessageArchive.Reader/Energinet.DataHub.MessageArchive.Reader.csproj, source/Energinet.DataHub.MessageArchive.Tests/Energinet.DataHub.MessageArchive.Tests.csproj, source/Energinet.Datahub.MessageArchive.Tests/MockedStorageWriter.cs
=> packages upgrade

build/infrastructure/main/app-webapi.tf, build/infrastructure/main/func-entrypoint.tf, build/infrastructure/main/kv-shared-resources.tf, build/infrastructure/main/variables.tf
updated terraform for HealthChecks
* #0000
=> updated terraform for HealthChecks

source/Energinet.DataHub.MessageArchive.Tests/Repositories/ArchiveReaderRepositoryTests.cs
=> removed unused using

.github/workflows/cd.yml, .github/workflows/ci.yml
Use of workflow 7.3.2 to see if we can retry Cosmos DB Install.
=> Use 7.3.2 workflow

build/infrastructure/main/app-webapi.tf, build/infrastructure/main/func-entrypoint.tf, build/infrastructure/main/kv-shared-access-policy.tf, build/infrastructure/main/kv-shared-resources.tf
Change keyvault references to mitigate risk of leaking sensitive information
https://github.com/Energinet-DataHub/the-outlaws/issues/334
=> Replace keyvault references

.github/workflows/cd.yml
=> merge workflows introduced in pr #67

.github/workflows/cd.yml
https://github.com/Energinet-DataHub/geh-message-archive/pull/92
=> Fix notify

source/Energinet.DataHub.MessageArchive.Persistence/ArchiveSearchRepository.cs
Resolves this issue https://github.com/Energinet-DataHub/geh-post-office/issues/828
=> Use contains instead of equels for messageid

source/Energinet.DataHub.MessageArchive.Common/Energinet.DataHub.MessageArchive.Common.csproj, source/Energinet.DataHub.MessageArchive.EntryPoint.WebApi/Energinet.DataHub.MessageArchive.EntryPoint.WebApi.csproj, source/Energinet.DataHub.MessageArchive.EntryPoint.WebApi/Startup.cs, source/Energinet.DataHub.MessageArchive.IntegrationTests/LocalSettings.cs
Should be merged with the other PR's For Auth/Middleware
=> refac: Use JWT permission middleware.
